# see all settings here: https://argoproj.github.io/argo-cd/operator-manual/application.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd
  namespace: default
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  project: default
  source:
    path: argo-cd-helm-apps/charts/argo-cd
    repoURL: https://github.com/blackwoodseven/k8s-init.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
