# This wrapper application - auto-loads all applications listed in the folder given below
# see all possible values here https://argoproj.github.io/argo-cd/operator-manual/application.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  project: default
  source:
    path: argo-cd-helm-apps/
    repoURL: https://github.com/blackwoodseven/k8s-init.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
