argo-cd:
  installCRDs: true
  global:
    image:
      tag: v1.8.4
#find latest tag here: https://github.com/argoproj/argo-helm/blob/master/charts/argo-cd/Chart.yaml (AppVersion)
  dex:
    enabled: false
  server:
    extraArgs:
      - --insecure
    config:
      repositories: |
        - type: helm
          name: stable
          url: https://charts.helm.sh/stable
        - type: helm
          name: argo-cd
          url: https://argoproj.github.io/argo-helm
        - type: git
          url: ssh://git@gitlab.enableit.dk:2223/kubernetes/argocd-apps.git
          sshPrivateKeySecret:
            name: gitlab-argocd-sshkey
            key: ssh-privatekey
