apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  project: default
  source:
    path: argo-cd-helm-apps/charts/argo-cd
    repoURL: ssh://git@gitlab.enableit.dk:2223/kubernetes/argocd-apps.git
    targetRevision: k8s-nuc8
    helm:
      valueFiles:
      - values.yaml
      - ../../k8s-nuc8/values-argo-cd.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
