apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd
  namespace: default
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  project: default
  source:
    path: argo-cd-helm-apps/charts/argo-cd
    repoURL: https://github.com/blackwoodseven/k8s-init.git
    targetRevision: HEAD
    helm:
      valueFiles:
      - values.yaml
      - ../../k8s-sre-cluster/values-argo-cd.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
