apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  project: default
  source:
    path: argo-cd-helm-apps/k8s-sre-cluster/
    repoURL: https://github.com/blackwoodseven/k8s-init.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
