argo-cd:
  installCRDs: false
  global:
    image:
      tag: v1.8.4
#find latest tag here: https://github.com/argoproj/argo-helm/blob/master/charts/argo-cd/Chart.yaml (AppVersion)
  dex:
    enabled: false
  configs: 
    knownHosts:
      data:
        ssh_known_hosts: |
          [gitlab.enableit.dk]:2223 ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBCayvWW9xSo/3nhXgu6A+O58aqTP/io/OD0jdU2UFM0XbC+yOK+0srE2847x7TzNpKMzHkWaCetXbGZak++KtFQ=
  server:
    extraArgs:
      - --insecure
    config:
      repositories: |
        - type: helm
          name: stable
          url: https://charts.helm.sh/stable
        - type: helm
          name: argo-cd
          url: https://argoproj.github.io/argo-helm
        - type: helm
          name: sealed-secrets
          url: https://bitnami-labs.github.io/sealed-secrets
        - type: git
          url: ssh://git@gitlab.enableit.dk:2223/kubernetes/argocd-apps.git
          sshPrivateKeySecret:
            name: argocd-sshkey
            key: ssh-privatekey
